repository:
  voucher:
    filePath: voucher.csv

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/voucher_mgmt?useSSL=false
    username: root
    password: root1234!
  batch:
    jdbc:
      schema: classpath:schema.sql

  sql:
    init:
      mode: always
